name: release github
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  release_github:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          pip install nox

      - name: Run tests
        shell: bash
        run: nox --force-color -s tests

      - name: Get previous version from latest tag
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.0.1"

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          version: ${{ steps.latest_tag.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
